### ISSUE TITLE
Platform backwards support

### ISSUE THREAD

**Issue by rcbevans** [deltakosh/Podcasts#14]
I can see from the appxmanifest that you're currently targeting RS1, and MinVersion is also RS1, however, for the platform extension SDKs you were referencing the TH2 extension SDKs.  Should the referenced extension SDKs be brought up to RS1.  I'm unsure if they offer bugfixes, or if it's just making the later extension SDK APIs available.

Now that RS2 is the current latest release from Microsoft, should target SDK be updated to RS2?  What level of legacy support do you want to maintain? 2 releases, so keep MinVersion at RS1 until whatever comes next comes along?

This means that the latest features can be incrementally added, but gives people chance to wait out initial release bugs if they choose?

**Comment by deltakosh** [comment]
RS1 is required because of the 1 process background audio
I plan to keep RS1 as minimum :)

**Comment by rcbevans** [comment]
Foreeeeveeeeer!?  Well, for now, that would work just fine.  I've created PR https://github.com/deltakosh/Podcasts/pull/16 which brings the targeting up to the latest RS2 release.  A side effect is that the project will no longer open with VS2015.

**Comment by deltakosh** [comment]
No problem for that
