### ISSUE TITLE
Car mode

### ISSUE THREAD

**Issue by deltakosh** [deltakosh/Podcasts#2]
Add a mode where the player controls are fullscreen
Mostlr useful while driving

**Comment by MMEnter** [comment]
Shoud it be another state of the shell.xaml triggered by a car button or another option in the menu?

**Comment by deltakosh** [comment]
Probably a button somewhere

**Comment by jongross4** [comment]
If possible, should detect bt associated with car and auto switch too.

**Comment by MMEnter** [comment]
![wp_ss_20170609_0004](https://user-images.githubusercontent.com/5066472/26989435-b003e2b6-4d18-11e7-8299-2dbd2565ff3b.png)
![wp_ss_20170609_0003](https://user-images.githubusercontent.com/5066472/26989436-b00aba5a-4d18-11e7-8484-b4717338aafe.png)
I created a new state that's triggered by the Car Button in the top left corner of the RootControlGrid.

**Comment by deltakosh** [comment]
This is really good

**Comment by MMEnter** [comment]
I never used GIT before, is there a way that I can commit my code for @deltakosh to review? When I try to Push I get a 403 error in VS17.

**Comment by deltakosh** [comment]
Just fork the repo and you will be able to submit a PR:)

**Comment by MMEnter** [comment]
This can be closed.
