### ISSUE TITLE
MVVM?

### ISSUE THREAD

**Issue by rcbevans** [deltakosh/Podcasts#22]
Currently the app is written with a lot of business logic in page behinds, rather than with an [MVVM](https://msdn.microsoft.com/en-us/library/hh848246.aspx) architecture.  This will potentially limit the extent to which code can be tested as UI is tightly coupled to business logic.  Is there any interest in migrating the app to an MVVM architecture?

**Comment by deltakosh** [comment]
Absolutely not:)

**Comment by rcbevans** [comment]
Alright then
