### ISSUE TITLE
Xbox - Background download unreliable

### ISSUE THREAD

**Issue by AnthonyBe** [deltakosh/Podcasts#25]
If you set up a library with a number of podcasts and then set retention settings, podcasts only seem to download when the app it actually launched on the Xbox. There does not seem to be background downloading?

In addition, I have had it say that my Xbox was on a metered connection on 1 occasion (no idea why) so I turned off the don't download/stream on metered connection options.

Often I have encountered that when I open the app and go to Downloads, I just get the 'bouncing balls' (hourglass) where the download status bar should be and it will stay like that forever. I have to reboot the Xbox to resolve and then the podcasts download. BTW, as a feature request it would be nice to see download speeds, ETA, etc. as sometimes it is hard to know if something is actually downloading.

**Comment by deltakosh** [comment]
Yep this is a known limitation of the xBox :(
