### ISSUE TITLE
Number of episodes per podcast

### ISSUE THREAD

**Issue by VGBenjamin** [deltakosh/Podcasts#27]
Hello,

I have just tested your podcast app. It looks great but I really think that they are a missing feature (or I didn't found the option). I would like to be able to override the defaut configuration "number of episodes to download" for a specific podcast. 

Thank you for your app, 

Regards,

Benjamin V

**Comment by deltakosh** [comment]
Good feedback. I do not plan to add support for per podcast configuration. But this is an OSS project so if someone wants to step in ;)

**Comment by deltakosh** [comment]
See #3
