### ISSUE TITLE
Downloading of episodes does not work

### ISSUE THREAD

**Issue by IstvanKohany** [deltakosh/Podcasts#28]
I chose my SD card to store downloaded episodes. After adding episodes to playlist I choose "download all". It looks like the program is downloading, but the folder od card remains empty. The same when I choose to download individual episodes.

Phone is Lumia 735 with Windows 10

**Comment by deltakosh** [comment]
And it works on the phone storage?

**Comment by IstvanKohany** [comment]
It doesn't. :-)

Well, I can choose to store files on SD card, but that's it. The app looks like it is downloading the files (the download bar for episodes is appering for example), but the folder I chose on SD card is empty and I can only listen to episodes by network (wifi or metered).

**Comment by deltakosh** [comment]
Ouch :( Do you have the same behavior on PC?

**Comment by IstvanKohany** [comment]
I don't know. PC app wasn't syncing with the mobile app, so I got rid of it. Will check in few hours.

**Comment by IstvanKohany** [comment]
OK, so I checked and its the same situation on the PC app. 

The app doesn't download the episodes as files to folder when I choose "external storage" in options. BTW, where are the files supposed to be stored, if I wouldn't tick "external storage"?

Is there any way to provide you with some kind of log from app, anything to help resolve this problem?

**Comment by deltakosh** [comment]
The will be saved only after being downloaded. Did you wait until the end?

**Comment by IstvanKohany** [comment]
> Did you wait until the end?

Of course :-)

**Comment by deltakosh** [comment]
Rats :) I would need to test it deeper because it works for me :(

**Comment by IstvanKohany** [comment]
> Rats :) I would need to test it deeper because it works for me :(

Please,  do :-) 

I like your app (and belive me, it's not so easy to find a likable podcast app on Windows mobile), but not beign able to download episodes is a kinda deal-breaker for me :-)

**Comment by deltakosh** [comment]
I tested on 3 differents computers and it works :(
Can you try to use the PC version and set the download to your desktop?
If this does not work I'm interested by an export of your podcasts :)

**Comment by IstvanKohany** [comment]
I tried with downloading to the desktop - no effect. The mobile app started to behave strangely. Earlier at least it look like it was downloading, now it's the moving pink dots all the time.
[subscriptions.zip](https://github.com/deltakosh/Podcasts/files/1050490/subscriptions.zip)

**Comment by deltakosh** [comment]
BUG FOUND!!
I'll send an update to the store! Thanks a lot for your kind patience!

**Comment by IstvanKohany** [comment]
Whoa, that was quick :-) Thanks for cooperation. Does that mean, that I can nitpick another things? :-)

**Comment by deltakosh** [comment]
It turned out that I have some time today. Won't guarantee it will be always the same :)
But please use issues to report issues / suggestions
