### ISSUE TITLE
White pages 

### ISSUE THREAD

**Issue by fraterdd** [deltakosh/Podcasts#29]
![wp_ss_20170605_0003](https://cloud.githubusercontent.com/assets/29207294/26793661/17ea36e8-4a1f-11e7-8085-232f81837bf6.png)
![wp_ss_20170605_0002](https://cloud.githubusercontent.com/assets/29207294/26793660/17e8f5da-4a1f-11e7-99df-ae335a14ae2e.png)

Hello,

After having reinitialized my Lumia 950, only the menus are visible.

The content of all the pages has turned completely white.

I've reinitialized the app, un/re-installed it, without any change.

Have you got a solution ?

Best regards,

David

**Comment by be9em0t** [comment]
I can confirm this. Lumia 950, reinitialized, fully updated - white pages. Same after switching to insider's Release preview build 16236

**Comment by deltakosh** [comment]
Only in options screen or in all screens?

**Comment by fraterdd** [comment]
In all screens.

**Comment by deltakosh** [comment]
Woot. Which version?

**Comment by be9em0t** [comment]
Hi david,

In all screens, both if I choose Sync or No sync on the firs question. Also I tried changing display scale from the default, same result.

Btw, great application, I love it!

Sent from my Windows 10 phone

**Comment by deltakosh** [comment]
Does it work on desktop?

**Comment by be9em0t** [comment]
Does not work on desktop, too. Version 7.6.1
Same version as  mobile - v. 7.6.1.

Sent from my Windows 10 phone

**Comment by deltakosh** [comment]
Ok bug found..Seems related to computer using insider preview. For now I'll revert a change done before and target RS1 SDK only.
Update should be in the store soon

**Comment by be9em0t** [comment]
Thank you, David, works like charm. I’ve also took care to update my review in the Store.

Btw, before the update problem existed both on normal and release preview mobile  devices. Something else, which I’ve never saw before: it wouldn’t let me install until I’ve updated Windows. So probably the SDK was too new.

Hope this helps.

Vla


Sent from my Windows 10 phone

**Comment by MMEnter** [comment]
Was the issue due to targeting CU and having RS1 as min version?

**Comment by deltakosh** [comment]
Yep:)

**Comment by MMEnter** [comment]
That's unfortunate! I was playing around with the new Compact View (it works/looks great) but I had to chance the target to CU. I guess I keep that one in my private branch.... .

**Comment by deltakosh** [comment]
Perhaps it was linked to some issues with insiders build.

**Comment by MMEnter** [comment]
Can we retarget it to RS2? I would love adding [CompactOverlay](https://blogs.msdn.microsoft.com/universal-windows-app-model/2017/02/11/compactoverlay-mode-aka-picture-in-picture/).
