### ISSUE TITLE
Podcasts Deleted on App Restart

### ISSUE THREAD

**Issue by hotgore** [deltakosh/Podcasts#41]
Every time I close the app or restart my phone my list of podcasts is wiped out. It tries to sync from onedrive, but crashes the app. Using Lumia 650, 10.0.15063.297

**Comment by deltakosh** [comment]
Are you a developer? if yes it could be cool to debug the project :)

**Comment by hotgore** [comment]
I am not a developer, but I can turn on dev mode and run whatever you need.

**Comment by deltakosh** [comment]
unfortunately you need visual studio :(

**Comment by deltakosh** [comment]
Does it do the same on PC?

**Comment by hotgore** [comment]
I haven't run the desktop version, but I can try it out.

**Comment by hotgore** [comment]
Turns out it was an issue with the OS build. Changed to slow stream for the insider builds and the issue has gone away. Thanks!

**Comment by psydesho** [comment]
I am having the same issue.  I updated the OS after reading this and 3 days later I am still experiencing this issue.  It syncs with OneDrive each every time the app opens and never keeps the most recent individual downloaded podcasts.  Not a developer and only using the mobile app.  Please help.

Lumia 1520 running Windows Phone Mobile 10.
