### ISSUE TITLE
wish - Run in Background and Check at a Set Interval for New Downloads

### ISSUE THREAD

**Issue by pgchase43228** [deltakosh/Podcasts#66]
Would like to have program run in background and check at a set interval, (anything from maybe once a day down to every 30 minutes), to check for new downloads. This would make it automated.

**Comment by pgchase43228** [comment]
Also, as a side comment, automatically Refresh when program is first started. Have program automatically start and run in background when Windows starts. You get the idea.

**Comment by pgchase43228** [comment]
Of course, it's not that hard to just start the program and hit refresh since I don't make use of the downloads until I show up anyway...

**Comment by Izzmo** [comment]
@pgchase43228 you closed this, did you not want it anymore? Seems like some decent ideas worth discussing.
