### ISSUE TITLE
Add an about page (On top of options)

### ISSUE THREAD

**Issue by deltakosh** [deltakosh/Podcasts#8]
- [x] Move the about from options to this page
- [x] Add a link to the repo issues

**Comment by aalok05** [comment]
I have created PR #10 . Please have a look as the page might need some more content, which I was not sure about.

**Comment by deltakosh** [comment]
Thanks @aalok05 ! I also moved the support buttons.

**Comment by deltakosh** [comment]
We should add a pivot in about to list contributors (starting with you :))

**Comment by aalok05** [comment]
That would be awesome! :)
